config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/..
  root to: "public/homes#top"
  resource :customers, only: [:edit, :update], module: 'public'
  resources :items, only: [:index, :show], module: 'public'
  delete 'cart_items/destroy_all' => "public/cart_items#destroy_all"

  resources :cart_items, only: [:index, :update, :destroy, :create], module: 'public'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy], module: 'public'

  post 'orders/confirm' => "public/orders#confirm"
  get 'orders/complete' => "public/orders#complete"
  resources :orders, only: [:new, :create, :index, :show], module: 'public'

  get 'customers/my_page' => "public/customers#show"
  get 'customers/unsubscribe' => "public/customers#unsubscribe"
  patch 'customers/withdraw' => "public/customers#withdraw"

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  # 管理者用
  # URL /admin/...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :customers, only: [:index]
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      collection do
        get 'search'
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end

  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, under_manufacture: 2, preparing_to_ship: 3, already_shipped: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  def are_all_details_completed?
    (order_details.completed_production.count == order_details.count) ? true : false # 製作ステータスが"製作完了"の数と注文詳細のレコードの数が一緒なら

    # if order_details.completed_production.count == order_details.count
    #   true
    # else
    #   false
    # end
    # と同じ!
  end

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params) && @order.status_before_type_cast == 1 # @orderがアプデできて, かつ 注文ステータスが "入金確認" (1)になった時
      # before_type_castでinteger型にcastする
      @order.order_details.update_all(making_status: 1) # 注文詳細の全製作ステータスを "製作待ち" (1)に変更
    end
    redirect_back(fallback_location: root_path)
    ## 方法としてはアリだけど見栄え悪い
    ## if @order.status == "payment_confirmation" # もし注文ステータスが "入金確認" だったら
    ##  @order.order_details.each do |order_detail| # 注文詳細に保存されている全商品をeachで回す
    ##    order_detail.making_status = "awaiting_manufacture" # 製作ステータスを "製作待ち" に変更
    ##    order_detail.update(making_status: order_detail.making_status)
    ##  end
    ## end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <h2>注文履歴一覧</h2>

  <table class="table">
    <thead>
      <tr>
        <th>
          購入日時
        </th>
        <th>
          購入者
        </th>
        <th>
          注文個数
        </th>
        <th>
          注文ステータス
        </th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td>
          <%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order), class: "text-dark" %>
        </td>
        <td>
          <%= order.customer.last_name + order.customer.first_name %>
        </td>
        <td>
          <%= order.order_details.sum(:amount) %>
        </td>
        <td>
          <%= order.status_i18n %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h2>注文履歴詳細</h2>

  <div class="row">
    <div class="col-md-8">
      <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
      <table class="table">
        <tr>
          <th>
            購入者
          </th>
          <td>
            <%= @order.customer.last_name + " " + @order.customer.first_name %>
          </td>
        </tr>
        <tr>
          <th>
            注文日
          </th>
          <td>
            <%= @order.created_at.strftime("%Y/%m/%d") %>
          </td>
        </tr>
        <tr>
          <th>
            配送先
          </th>
          <td>
            <%= @order.address_display %>
          </td>
        </tr>
        <tr>
          <th>
            支払方法
          </th>
          <td>
            <%= @order.payment_method_i18n %>
          </td>
        </tr>
        <tr>
          <th>
            注文ステータス
          </th>
          <td>
            <%= f.select :status, Order.statuses_i18n.invert %>
          </td>
          <td>
            <%= f.submit '更新',class: "btn btn-success" %>
          </td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @order.order_details.each do |order_detail| %>
          <tr>
            <td>
              <%= order_detail.item.name %>
            </td>
            <td>
              <%= order_detail.item.with_tax_price.to_s(:delimited) %>
            </td>
            <td>
              <%= order_detail.amount %>
            </td>
            <td>
              <%= order_detail.price.to_s(:delimited) %>
            </td>
            <td>
              <%= form_with model: order_detail, url: admin_order_order_detail_path(order_id: @order.id, id: order_detail.id) do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                <%= f.submit '更新', class: "btn btn-success" %>
              <% end %>
            </td>
            <td>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>