config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/..
  root to: "public/homes#top"
  resource :customers, only: [:edit, :update], module: 'public'
  resources :items, only: [:index, :show], module: 'public'
  delete 'cart_items/destroy_all' => "public/cart_items#destroy_all"

  resources :cart_items, only: [:index, :update, :destroy, :create], module: 'public'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy], module: 'public'

  post 'orders/confirm' => "public/orders#confirm"
  get 'orders/complete' => "public/orders#complete"
  resources :orders, only: [:new, :create, :index, :show], module: 'public'

  get 'customers/my_page' => "public/customers#show"
  get 'customers/unsubscribe' => "public/customers#unsubscribe"
  patch 'customers/withdraw' => "public/customers#withdraw"

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  # 管理者用
  # URL /admin/...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :customers, only: [:index]
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      collection do
        get 'search'
      end
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end

  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  # 小計 計算メソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  # is_deletedがfalseならtrueを返す
  # def active_for_authentication?
  #   super && (self.is_deleted == false)
  # end

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  has_one_attached :image
  
  has_rich_text :content

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  # validates :is_active, presence: true

  #消費税 計算メソッド
  def with_tax_price
    (price * 1.1).floor # floorを用いて小数点以下切り捨て
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, under_manufacture: 2, preparing_to_ship: 3, already_shipped: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  def are_all_details_completed?
    (order_details.completed_production.count == order_details.count) ? true : false # 製作ステータスが"製作完了"の数と注文詳細のレコードの数が一緒なら

    # if order_details.completed_production.count == order_details.count
    #   true
    # else
    #   false
    # end
    # と同じ!
  end

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { cannot_be_started: 0, awaiting_manufacture: 1, under_manufacture: 2, completed_production: 3 }

  belongs_to :item
  belongs_to :order
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show # 研修要件に無い部分
    @item = Item.find(params[:id])
  end

  def edit # 研修要件に無い部分
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update # 研修要件に無い部分
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  # 商品検索機能(部分一致) 新たにsearchアクションを定義
  def search
    if params[:name].present?
      @items = Item.where('name LIKE ?', "%#{params[:name]}%")
    else
      @items = Item.all
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
    when Customer
      flash[:notice] = "ようこそ、#{resource.last_name}さん！"
      customers_my_page_path
    when Admin
      admin_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :customer
      root_path
    when :admin
      new_admin_session_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <% if customer_signed_in? %>
            <a class="navbar-brand p-3" href="/"><span>LOGO</span></a>
          <% elsif admin_signed_in? %>
            <a class="navbar-brand p-3" href="/admin"><span>LOGO</span></a>
          <% else %>
            <a class="navbar-brand p-3" href="/"><span>LOGO</span></a>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary text-dark" %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary text-dark" %>
                </li>
              <% else %>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
                <li class="nav-item nav-link text-dark">
                  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary text-dark" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="float-right">
        <%= form_with url: search_admin_items_path, local:true, method: :get do |f| %> <!-- 検索機能の実装 -->
          <%= f.text_field :name %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
      <div class="flash_message">
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>

  </body>
</html>